---
language: ruby
bundler_args: --without development
script: "bundle exec rake test SPEC_OPTS='--format documentation'"
rvm:
  - 1.9.3
  - 2.1.9
  - 2.4.1
env:
  matrix:
    - MCOLLECTIVE_GEM_VERSION="~> 2.7.0"
    - MCOLLECTIVE_GEM_VERSION="~> 2.10.0"
    - MCOLLECTIVE_GEM_VERSION="~> 2.11.0"
notifications:
  email: false
